### PR TITLE
Update nilearn material for MAIN workshop 2022

### PR DESCRIPTION
**Pull request by ymzayek**

### CODE REVIEW

**Comment by htwangtw** [comment]
LGTM so far! @ymzayek I am happy to merge it

**Comment by ymzayek** [comment]
@htwangtw yes it's ok with me!

**Comment by ymzayek** [comment]
@htwangtw let me know if there's anything left to do on this. Otherwise, I think it can be merged :)

**Comment by htwangtw** [comment]
Oops I forgot to merge it that was all! Merging ..

**Pull request merged**
